# Generated by Django 5.2.8 on 2025-11-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Nombre de la categoría, por ejemplo: 'Belleza'.", max_length=100, unique=True, verbose_name='Título')),
                ('icon', models.CharField(help_text="Identificador del ícono, por ejemplo: 'scissors'.", max_length=50, verbose_name='Ícono')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['title'],
            },
        ),
    ]
