# Generated by Django 5.2.8 on 2025-11-27 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Nombre del servicio, por ejemplo: 'Corte de cabello'.", max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, help_text='Descripción detallada del servicio.', verbose_name='Descripción')),
                ('price', models.DecimalField(decimal_places=2, help_text='Precio del servicio.', max_digits=10, verbose_name='Precio')),
                ('duration', models.PositiveIntegerField(help_text='Duración del servicio en minutos.', verbose_name='Duración')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el servicio está disponible.', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('category', models.ForeignKey(help_text='Categoría a la que pertenece el servicio.', on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['title'],
                'unique_together': {('category', 'title')},
            },
        ),
    ]
